### ISSUE TITLE
Add a Hand class

### ISSUE THREAD

**Issue by zooba** [zooba/deck#7]
This should make it easy to handle dealing, comparison, set operations, and rendering of hands of cards.

**Comment by grahambrown1** [comment]
@zooba - will you be releasing to PyPi with this change? At the moment the readme references the Hand class that isn't in latest/default version (3.0.0) currently available on PyPi.
Thanks

**Comment by zooba** [comment]
@grahambrown1 Have you tried with the `--pre` version that's up there? I've only used the class in a single project so far, so I'm not _quite_ confident to call it stable and would love a second opinion.

**Comment by grahambrown1** [comment]
I got it by specifying the version, thanks.
I've only just started having a look (heard you talk about it on Python Bytes), got tripped up initially following the readme when the Hand class wasn't in the package I had.
I'll probably have another play this weekend will let you know how it goes.
Are you OK for me to create issues if I do spot something?

**Comment by zooba** [comment]
Of course! Maintenance isn't a high priority for me, but I'll see things you post eventually. Feel free to do PRs as well if it needs straightforward fixes.
